services:
  - type: web
    name: elite-vc-music-bot
    runtime: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: python3 main.py

    envVars:
      - key: API_ID
        sync: false

      - key: API_HASH
        sync: false

      - key: BOT_TOKEN
        sync: false

      - key: STRING_SESSION
        sync: false

      - key: OWNER_ID
        sync: false

    autoDeploy: true
